name:                purescript-iso
version:             0.0.1.1
git:                 "git://git.localcooking.com/tooling/purescript-iso.git"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 (c) Local Cooking Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Isomorphic trivial data type definitions over JSON
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/purescript-iso#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- async
- attoparsec-uri >= 0.0.5.1 && < 0.0.6
- bytestring
- containers
- monad-control
- mtl
- stm
- strict
- text
- QuickCheck
- quickcheck-instances
- utf8-string
- uuid
- zeromq4-haskell
- zeromq4-simple

library:
  source-dirs: src

tests:
  purescript-iso-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purescript-iso
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - time
